### PR TITLE
Issues fixed

### PR DESCRIPTION
**Pull request by zlayabekrija**
Kindly review code fixes.

### CODE REVIEW

**Comment by talihomz** [comment]
Done, everything looks great! 👍

Move on to the next project.


Side Note: You can improve on the look of the page later on, and make it look more like Youtube. This is strictly not necessary, but it would look great as part of your portfolio projects later on.

**Comment by zlayabekrija** [comment]
Thanks for the review. What exactly should we improve?

**Comment by talihomz** [comment]
I'm comparing [your implementation](https://raw.githubusercontent.com/zlayabekrija/youtube-clone/master/index.html) with a real YouTube page. Here are my thoughts:

1. The button in the search bar and subscribe have a border unlike Youtube.
2. The comment text area seems to have a different font size for the text compared to the placeholder `Add a public comment`.
3. Also, it wouldn't hurt to add a few comment elements, just to improve on the overall look.

Other than that, you can add more improvements to make it look as close as possible to Youtube.

**Comment by talihomz** [comment]
Wait, @zlayabekrija  @inhaq  did you merge this PR or just close it?

**Comment by talihomz** [comment]
How did you integrate the changes into the master branch?

**Comment by talihomz** [comment]
I gave it a :+1:

**Pull request closed without merging**
